#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

unless ARGV[0] && ARGV[1]
  ErpHelper.logger "Usage: shipping_charge fedex_code shipping_points"
  exit
end

results = ProductShippingRate.fedex_shipping_options(ARGV[0], ARGV[1].to_f)
if results.empty?
  ErpHelper.logger 'Query result is empty!'
else
  results.each do |result|
    ErpHelper.logger "#{result.delivery_mode} : $#{result.shipping_charge} : #{result.description}"
  end
end

