# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 86) do

  create_table "agreement_logs", :force => true do |t|
    t.column "agreement_version_id", :integer, :default => 0, :null => false
    t.column "store_user_id", :integer
    t.column "download_id", :integer
    t.column "order_id", :integer
    t.column "remote_ip", :string
    t.column "created_at", :datetime
    t.column "http_header", :text
    t.column "name", :string
    t.column "email_address", :string
    t.column "order_number", :string
    t.column "remote_location", :string
    t.column "agreement_name", :string
    t.column "agreement_version", :string
    t.column "download_name", :string
    t.column "download_version", :string
  end

  create_table "agreement_versions", :force => true do |t|
    t.column "agreement_id", :integer, :default => 0, :null => false
    t.column "content", :text, :default => "", :null => false
    t.column "version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "agreements", :force => true do |t|
    t.column "name", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "agreements", ["name"], :name => "name"

  create_table "ax_account_addresses", :force => true do |t|
    t.column "ax_account_id", :integer
    t.column "ax_account_number", :string
    t.column "address_type", :string
    t.column "address", :string
    t.column "city", :string
    t.column "country_region_id", :string, :limit => 20
    t.column "state", :string, :limit => 20
    t.column "street", :string
  end

  create_table "ax_account_contact_people", :force => true do |t|
    t.column "ax_account_id", :integer
    t.column "email", :string, :default => "", :null => false
    t.column "first_name", :string, :default => "", :null => false
    t.column "last_name", :string, :default => "", :null => false
    t.column "name", :string, :default => "", :null => false
    t.column "selected_address", :string, :default => "", :null => false
  end

  create_table "ax_accounts", :force => true do |t|
    t.column "ax_account_number", :string, :limit => 20
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "currency", :string, :limit => 20
    t.column "cust_first_name", :string
    t.column "cust_last_name", :string
    t.column "email", :string
    t.column "cust_group", :string, :limit => 20
    t.column "language_id", :string, :limit => 20
    t.column "phone", :string
    t.column "address", :string
    t.column "city", :string
    t.column "country_region_id", :string
    t.column "state", :string, :limit => 20
    t.column "street", :string
    t.column "created_date", :date
    t.column "modified_date", :date
    t.column "status", :string, :limit => 20
    t.column "updated_at", :datetime
    t.column "red_one_shipped", :string, :limit => 16, :default => "No"
    t.column "assign_to", :string, :limit => 32, :default => "", :null => false
    t.column "zip_code", :string, :default => "", :null => false
    t.column "tele_prod_tax_exempt", :string, :default => "", :null => false
  end

  add_index "ax_accounts", ["ax_account_number"], :name => "ax_accounts_ax_account_number_index"

  create_table "ax_inventories", :force => true do |t|
    t.column "dim_group_id", :string, :limit => 10, :default => "", :null => false
    t.column "item_group_id", :string, :limit => 10, :default => "", :null => false
    t.column "item_id", :string, :limit => 10, :default => "", :null => false
    t.column "item_name", :string, :default => "", :null => false
    t.column "item_price", :float, :default => 0.0, :null => false
    t.column "model_group_id", :string, :limit => 10, :default => "", :null => false
    t.column "pct_deposit", :float, :default => 0.0, :null => false
    t.column "amt_deposit", :float, :default => 0.0, :null => false
    t.column "shipping_points", :float, :default => 0.0, :null => false
    t.column "status", :string, :limit => 10, :default => "", :null => false
    t.column "updated_at", :datetime
  end

  add_index "ax_inventories", ["item_id"], :name => "ax_inventories_item_id_index"
  add_index "ax_inventories", ["item_name"], :name => "ax_inventories_item_name_index"
  add_index "ax_inventories", ["item_price"], :name => "ax_inventories_item_price_index"
  add_index "ax_inventories", ["pct_deposit"], :name => "ax_inventories_pct_deposit_index"
  add_index "ax_inventories", ["amt_deposit"], :name => "ax_inventories_amt_deposit_index"

  create_table "ax_order_line_items", :force => true do |t|
    t.column "ax_order_number", :string, :limit => 20
    t.column "ax_order_id", :integer
    t.column "confirmed_lv", :date
    t.column "delivered_in_total", :integer
    t.column "invoiced_in_total", :integer
    t.column "item_id", :string, :limit => 20
    t.column "remain_sales_physical", :integer
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :integer
    t.column "sales_unit", :string, :limit => 20
    t.column "updated_at", :datetime
  end

  add_index "ax_order_line_items", ["ax_order_id"], :name => "ax_order_line_items_ax_order_id_index"
  add_index "ax_order_line_items", ["item_id"], :name => "ax_order_line_items_item_id_index"
  add_index "ax_order_line_items", ["remain_sales_physical"], :name => "ax_order_line_items_remain_sales_physical_index"
  add_index "ax_order_line_items", ["sales_item_reservation_number"], :name => "ax_order_line_items_sales_item_reservation_number_index"

  create_table "ax_orders", :force => true do |t|
    t.column "ax_order_number", :string, :limit => 20
    t.column "ax_account_id", :integer
    t.column "ax_account_number", :string, :limit => 20
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string, :limit => 20
    t.column "delivery_county", :string
    t.column "delivery_date", :date
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "delivery_zip_code", :string
    t.column "purch_order_form_num", :string
    t.column "sales_tax", :float
    t.column "shipping_charges", :float
    t.column "discounts", :float
    t.column "created_date", :date
    t.column "modified_date", :date
    t.column "sales_status", :string
    t.column "status", :string, :limit => 20
    t.column "updated_at", :datetime
  end

  add_index "ax_orders", ["ax_order_number"], :name => "ax_orders_ax_order_number_index"
  add_index "ax_orders", ["ax_account_id"], :name => "ax_orders_ax_account_id_index"

  create_table "ax_shipping_rates", :force => true do |t|
    t.column "shipping_zone", :string, :limit => 10, :default => "", :null => false
    t.column "code", :string, :limit => 10, :default => "", :null => false
    t.column "min_points", :float, :default => 0.0, :null => false
    t.column "max_points", :float, :default => 0.0, :null => false
    t.column "retail_price", :float, :default => 0.0, :null => false
    t.column "status", :string, :limit => 10, :default => "EMPTY", :null => false
    t.column "updated_at", :datetime
  end

  add_index "ax_shipping_rates", ["shipping_zone"], :name => "ax_shipping_rates_shipping_zone_index"
  add_index "ax_shipping_rates", ["code"], :name => "ax_shipping_rates_code_index"
  add_index "ax_shipping_rates", ["min_points"], :name => "ax_shipping_rates_min_points_index"
  add_index "ax_shipping_rates", ["max_points"], :name => "ax_shipping_rates_max_points_index"
  add_index "ax_shipping_rates", ["retail_price"], :name => "ax_shipping_rates_retail_price_index"

  create_table "ax_store_user_logs", :force => true do |t|
    t.column "email_address", :string
    t.column "raw_input", :text
    t.column "status", :string
    t.column "message", :text
    t.column "return_message", :text
    t.column "created_at", :datetime
    t.column "created_on", :date
    t.column "updated_at", :datetime
  end

  create_table "contact_ticket_black_lists", :force => true do |t|
    t.column "email", :string
  end

  create_table "contact_ticket_logs", :force => true do |t|
    t.column "contact_ticket_id", :integer, :default => 0, :null => false
    t.column "message", :text
    t.column "response_body", :text
    t.column "response_code", :string
    t.column "created_at", :datetime, :null => false
  end

  create_table "contact_tickets", :force => true do |t|
    t.column "post_data", :text
    t.column "is_completed", :boolean, :default => false
    t.column "created_at", :datetime, :null => false
  end

  create_table "content_node_types", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
  end

  create_table "content_nodes", :force => true do |t|
    t.column "name", :string, :limit => 200, :default => "", :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "content", :text, :default => "", :null => false
    t.column "display_on", :datetime, :null => false
    t.column "created_on", :datetime, :null => false
    t.column "content_node_type_id", :integer, :default => 1, :null => false
  end

  add_index "content_nodes", ["name"], :name => "name"

  create_table "countries", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "fedex_code", :string, :limit => 50
    t.column "ufsi_code", :string, :limit => 3
    t.column "number_of_orders", :integer, :default => 0, :null => false
    t.column "fedex_zone", :string, :limit => 16, :default => "", :null => false
  end

  add_index "countries", ["number_of_orders"], :name => "number_of_orders"

  create_table "delivery_modes", :force => true do |t|
    t.column "code", :string
    t.column "description", :text
  end

  create_table "download_categories", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text
    t.column "agreement_id", :integer
    t.column "code", :string
    t.column "disable", :boolean, :default => false
    t.column "display_pattern", :string
    t.column "position", :integer
    t.column "download_type", :string
    t.column "movie_url", :string
    t.column "movie_size", :string
    t.column "movie_duration", :string
  end

  create_table "downloads", :force => true do |t|
    t.column "download_category_id", :integer
    t.column "version_major", :integer
    t.column "version_minor", :integer
    t.column "version_revision", :integer
    t.column "windows", :boolean
    t.column "mac", :boolean
    t.column "release_note", :text
    t.column "release_date", :date
    t.column "filename", :string
    t.column "filesize", :integer
    t.column "created_at", :datetime
    t.column "restrict", :boolean, :default => true
    t.column "build_number", :integer
  end

  create_table "email_announcements", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "email_address", :string, :default => "", :null => false
    t.column "industry", :string
    t.column "editor", :string
    t.column "system", :string
    t.column "comments", :text
    t.column "hd_camera", :string
    t.column "raw_camera", :string
  end

  create_table "erp_addresses", :force => true do |t|
    t.column "city", :string
    t.column "country_region_id", :string
    t.column "state", :string
    t.column "street", :string
    t.column "zip_code", :string
    t.column "address", :text
    t.column "county", :string
    t.column "country", :string
    t.column "record_id", :string, :default => "0", :null => false
    t.column "address_type", :string
    t.column "hash", :string
    t.column "parent_id", :integer
    t.column "type", :string
    t.column "name", :string
  end

  add_index "erp_addresses", ["hash"], :name => "erp_addresses_hash_index"
  add_index "erp_addresses", ["type"], :name => "erp_addresses_type_index"
  add_index "erp_addresses", ["parent_id"], :name => "erp_addresses_parent_id_index"

  create_table "erp_contact_people", :force => true do |t|
    t.column "erp_customer_id", :integer, :default => 0, :null => false
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "name", :string
    t.column "email", :string
    t.column "newly_created", :boolean, :default => true, :null => false
    t.column "created_at", :datetime
  end

  add_index "erp_contact_people", ["erp_customer_id"], :name => "erp_contact_people_erp_customer_id_index"

  create_table "erp_customers", :force => true do |t|
    t.column "account_num", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "group", :string, :default => "INT", :null => false
    t.column "discounts", :float, :limit => 18
    t.column "email", :string
    t.column "language_id", :string, :default => "en_us", :null => false
    t.column "erp_modstamp", :datetime
    t.column "phone", :string
    t.column "account_balance", :float, :limit => 10
    t.column "currency", :string, :default => "USD", :null => false
    t.column "red_one_shipped", :boolean, :default => false, :null => false
    t.column "assigned_to", :string, :limit => 100
    t.column "ship_to_id", :integer
    t.column "bill_to_id", :integer
    t.column "name", :string
    t.column "delivery_mode", :string
    t.column "synchronized", :boolean, :default => true, :null => false
    t.column "updated_at", :datetime
    t.column "created_date", :datetime
    t.column "to_transfer", :float, :limit => 18
    t.column "camera", :integer
    t.column "subtotal", :float, :limit => 18
    t.column "tax", :float, :limit => 18
    t.column "balance", :float, :limit => 18
    t.column "transfer_amount", :float, :limit => 18
    t.column "shipping", :float, :limit => 18
    t.column "shipping_method", :string
  end

  add_index "erp_customers", ["id"], :name => "erp_customers_id_index"
  add_index "erp_customers", ["account_num"], :name => "erp_customers_account_num_index"
  add_index "erp_customers", ["synchronized"], :name => "erp_customers_synchronized_index"

  create_table "erp_items", :force => true do |t|
    t.column "item_id", :string, :default => "", :null => false
    t.column "name", :string, :default => "", :null => false
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "group_id", :string, :default => "", :null => false
    t.column "dim_group_id", :string, :default => "", :null => false
    t.column "model_group_id", :string, :default => "", :null => false
    t.column "price", :float
    t.column "percent_deposit", :float
    t.column "amount_deposit", :float
    t.column "shipping_points", :float
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "dangerous", :boolean, :default => false
  end

  create_table "erp_logs", :force => true do |t|
    t.column "code", :integer
    t.column "response", :text
    t.column "message", :text
    t.column "uuid", :string
    t.column "post_body", :text
    t.column "service_url", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "update_complete", :boolean
    t.column "account_num", :string
    t.column "sales_id", :string
    t.column "error_description", :text
    t.column "email_sent", :boolean, :default => false
  end

  add_index "erp_logs", ["uuid"], :name => "erp_logs_uuid_index"

  create_table "erp_order_logs", :force => true do |t|
    t.column "erp_order_id", :integer
    t.column "uuid", :string, :limit => 40
    t.column "order_number", :string
    t.column "erp_serv", :string
    t.column "log_msg", :string
    t.column "xml", :text
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "erp_sales_lines", :force => true do |t|
    t.column "erp_sales_order_id", :integer, :default => 0, :null => false
    t.column "confirmed_dlv", :string
    t.column "item_id", :string, :default => "", :null => false
    t.column "remain_sales_physical", :float, :limit => 10, :default => 0.0, :null => false
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :float, :limit => 10
    t.column "sales_price", :float, :limit => 12
    t.column "line_amount", :float, :limit => 18
    t.column "line_percent", :string
    t.column "sales_unit", :string, :default => "Ea", :null => false
    t.column "delivered_in_total", :float, :limit => 10
    t.column "invoiced_in_total", :float, :limit => 10
    t.column "invent_trans_id", :string
    t.column "updated_at", :datetime
    t.column "completed", :boolean, :default => false, :null => false
  end

  add_index "erp_sales_lines", ["erp_sales_order_id"], :name => "erp_sales_lines_erp_sales_order_id_index"
  add_index "erp_sales_lines", ["item_id"], :name => "erp_sales_lines_item_id_index"

  create_table "erp_sales_orders", :force => true do |t|
    t.column "sales_id", :string
    t.column "erp_customer_id", :integer, :default => 0, :null => false
    t.column "delivery_date", :date
    t.column "modified_date", :date
    t.column "purch_order_form_num", :string
    t.column "sales_status", :string
    t.column "shipping_charges", :float, :limit => 10
    t.column "delivery_mode_id", :string
    t.column "completed", :boolean, :default => false, :null => false
    t.column "document_status", :string
    t.column "erp_modstamp", :datetime
    t.column "sales_tax", :float, :limit => 10
    t.column "synchronized", :boolean, :default => true, :null => false
    t.column "updated_at", :datetime
    t.column "deleted", :boolean, :default => false
  end

  add_index "erp_sales_orders", ["erp_customer_id"], :name => "erp_sales_orders_erp_customer_id_index"
  add_index "erp_sales_orders", ["completed"], :name => "erp_sales_orders_completed_index"
  add_index "erp_sales_orders", ["synchronized"], :name => "erp_sales_orders_synchronized_index"

  create_table "events", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "description", :text
  end

  create_table "example_configuration_products", :force => true do |t|
    t.column "example_configuration_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "product_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "quantity", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "example_configurations", :force => true do |t|
    t.column "name", :string, :limit => 45, :default => "", :null => false
    t.column "description", :text
    t.column "position", :integer, :limit => 10
  end

  create_table "film_clips", :force => true do |t|
    t.column "account_num", :string, :limit => 16
    t.column "email", :string, :limit => 128
    t.column "name", :string, :limit => 64
    t.column "title", :string
    t.column "studio", :string, :limit => 64
    t.column "producer", :string, :limit => 64
    t.column "director", :string, :limit => 64
    t.column "dp", :string, :limit => 64
    t.column "camera_sn", :string, :limit => 64
    t.column "lenses_used", :string, :limit => 64
    t.column "film_type", :string
    t.column "summary", :text
    t.column "release_date", :date
    t.column "website_url", :string
    t.column "trailer_url", :string
    t.column "actual_footage_url", :string
    t.column "cast", :string
    t.column "authorized", :boolean, :default => false, :null => false
    t.column "sticked", :boolean, :default => false, :null => false
    t.column "position", :integer
    t.column "thumbnail_file_name", :string
    t.column "thumbnail_content_type", :string
    t.column "thumbnail_file_size", :integer
    t.column "thumbnail_updated_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "film_clips", ["account_num"], :name => "film_clips_account_num_index"

  create_table "ftp_test", :force => true do |t|
    t.column "version", :string
    t.column "Is_last_version", :boolean, :default => false, :null => false
    t.column "ftp_hosts", :string
    t.column "update_file", :string
    t.column "created_at", :timestamp, :null => false
    t.column "updated_at", :timestamp, :null => false
  end

  create_table "images", :force => true do |t|
    t.column "path", :string, :default => "", :null => false
    t.column "description", :string
    t.column "width", :integer, :default => 0, :null => false
    t.column "height", :integer, :default => 0, :null => false
  end

  create_table "images_products", :id => false, :force => true do |t|
    t.column "image_id", :integer, :default => 0, :null => false
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "sort_order", :integer
  end

  add_index "images_products", ["product_id", "image_id"], :name => "main"

  create_table "jan_line_items", :force => true do |t|
    t.column "order_id", :integer, :default => 0, :null => false
    t.column "product", :string, :default => "", :null => false
    t.column "subproduct", :string
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "price", :float, :limit => 19, :default => 0.0, :null => false
    t.column "serial_no", :integer, :limit => 6
    t.column "created", :datetime
    t.column "modified", :datetime
  end

  create_table "jan_orders", :force => true do |t|
    t.column "order_number", :string, :limit => 30
    t.column "account_id", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 128
    t.column "firstname", :string, :limit => 64, :default => "", :null => false
    t.column "lastname", :string, :limit => 64, :default => "", :null => false
    t.column "email", :string, :limit => 64, :default => "", :null => false
    t.column "phone", :string, :limit => 32, :default => "", :null => false
    t.column "address", :string, :limit => 64, :default => "", :null => false
    t.column "address_two", :string, :limit => 128
    t.column "postcode", :string, :limit => 10, :default => "0", :null => false
    t.column "city", :string, :limit => 64, :default => "", :null => false
    t.column "state", :string
    t.column "country", :string, :limit => 64, :default => "", :null => false
    t.column "shipping_method", :string, :limit => 100, :default => "", :null => false
    t.column "shipping_price", :float, :limit => 19, :default => 0.0, :null => false
    t.column "payment_method", :string, :limit => 100, :default => "", :null => false
    t.column "payment_price", :float, :limit => 19, :default => 0.0, :null => false
    t.column "payment_pending", :string, :limit => 1, :default => "Y"
    t.column "contract_required", :string, :limit => 1, :default => "N"
    t.column "contract_sent", :datetime
    t.column "comments", :text
    t.column "created", :datetime
    t.column "modified", :datetime
    t.column "viaklix_trx_id", :string
  end

  create_table "mail_task_feb_nearly_ready_to_ship_queue_line_items", :force => true do |t|
    t.column "mail_task_feb_nearly_ready_to_ship_queue_id", :integer
    t.column "ax_order_number", :string
    t.column "confirmed_lv", :string
    t.column "delivered_in_total", :integer
    t.column "invoiced_in_total", :integer
    t.column "item_id", :string
    t.column "item_name", :string
    t.column "remain_sales_physical", :integer
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :integer
    t.column "sales_unit", :string
    t.column "price", :float, :default => 0.0
    t.column "delivery_message", :string
  end

  create_table "mail_task_feb_nearly_ready_to_ship_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "mail_task_feb_nearly_ready_to_ship_queues", ["sid"], :name => "mail_task_feb_nearly_ready_to_ship_queues_sid_index"

  create_table "mail_task_feb_offical_red_delivery_policies", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "serial_numbers", :string
  end

  create_table "mail_task_feb_ready_to_ship_queue_line_items", :force => true do |t|
    t.column "mail_task_feb_ready_to_ship_queue_id", :integer
    t.column "ax_order_number", :string
    t.column "confirmed_lv", :string
    t.column "delivered_in_total", :integer
    t.column "invoiced_in_total", :integer
    t.column "item_id", :string
    t.column "item_name", :string
    t.column "remain_sales_physical", :integer
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :integer
    t.column "sales_unit", :string
    t.column "price", :float, :default => 0.0
    t.column "delivery_message", :string
  end

  create_table "mail_task_feb_ready_to_ship_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "mail_task_feb_ready_to_ship_queues", ["sid"], :name => "mail_task_feb_ready_to_ship_queues_sid_index"

  create_table "mail_task_feb_red_invited_one_hundred_to_three_hundred_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "serial_numbers", :string
  end

  create_table "mail_task_jan_prepare_delivery_queue_line_items", :force => true do |t|
    t.column "mail_task_jan_prepare_delivery_queue_id", :integer
    t.column "ax_order_number", :string
    t.column "confirmed_lv", :string
    t.column "delivered_in_total", :integer
    t.column "invoiced_in_total", :integer
    t.column "item_id", :string
    t.column "item_name", :string
    t.column "remain_sales_physical", :integer
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :integer
    t.column "sales_unit", :string
    t.column "price", :float, :default => 0.0
    t.column "delivery_message", :string
  end

  create_table "mail_task_jan_prepare_delivery_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "readed_at", :datetime
  end

  add_index "mail_task_jan_prepare_delivery_queues", ["sid"], :name => "mail_task_jan_prepare_delivery_queues_sid_index"

  create_table "mail_task_jan_ready_to_ship_queue_line_items", :force => true do |t|
    t.column "mail_task_jan_ready_to_ship_queue_id", :integer
    t.column "ax_order_number", :string
    t.column "confirmed_lv", :string
    t.column "delivered_in_total", :integer
    t.column "invoiced_in_total", :integer
    t.column "item_id", :string
    t.column "item_name", :string
    t.column "remain_sales_physical", :integer
    t.column "sales_item_reservation_number", :string
    t.column "sales_qty", :integer
    t.column "sales_unit", :string
    t.column "price", :float, :default => 0.0
    t.column "delivery_message", :string
  end

  create_table "mail_task_jan_ready_to_ship_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "mail_task_jan_ready_to_ship_queues", ["sid"], :name => "mail_task_jan_ready_to_ship_queues_sid_index"

  create_table "mail_task_jan_redone_delivery_policy_six_to_five_hundred_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "serial_numbers", :string
  end

  create_table "mail_task_jan_redone_delivery_policy_update_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "account_balance", :float, :default => 0.0
    t.column "discounts", :float, :default => 0.0
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "phone", :string
    t.column "contact_person_name", :string
    t.column "contact_person_select_address", :string
    t.column "address", :string
    t.column "invoice_address", :string
    t.column "invoice_city", :string
    t.column "invoice_country_region_id", :string
    t.column "invoice_state", :string
    t.column "invoice_street", :string
    t.column "delivery_address", :string
    t.column "delivery_city", :string
    t.column "delivery_country_region_id", :string
    t.column "delivery_state", :string
    t.column "delivery_street", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "readed_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "serial_numbers", :string
  end

  create_table "mail_task_redone_serial_number_notify_queues", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "ax_account_number", :string
    t.column "ax_order_number", :string
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "serial_number", :string
    t.column "purch_order_form_num", :string
    t.column "complete", :boolean, :default => false
    t.column "sid", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "readed_at", :datetime
  end

  add_index "mail_task_redone_serial_number_notify_queues", ["sid"], :name => "mail_task_redone_serial_number_notify_queues_sid_index"

  create_table "mail_task_redone_serial_number_notify_sent_logs", :force => true do |t|
    t.column "mail_task_redone_serial_number_notify_queue_id", :integer
    t.column "to", :string
    t.column "subject", :string
    t.column "body", :text
    t.column "sent", :boolean
    t.column "created_at", :datetime
  end

  create_table "mail_task_sent_logs", :force => true do |t|
    t.column "mail_task_id", :integer
    t.column "mail_queue_id", :integer
    t.column "from", :string
    t.column "to", :string
    t.column "subject", :string
    t.column "body", :text
    t.column "sent", :boolean
    t.column "created_at", :datetime
  end

  create_table "mail_tasks", :force => true do |t|
    t.column "task_name", :string
    t.column "task_description", :text
    t.column "table_name", :string
    t.column "task_date", :date
    t.column "available", :boolean, :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "my_account_logs", :force => true do |t|
    t.column "email", :string
    t.column "account_num", :string
    t.column "sales_order_num", :string
    t.column "class_name", :string
    t.column "record_id", :integer
    t.column "action", :string
    t.column "description", :string
    t.column "remote_ip", :string
    t.column "remote_location", :string
    t.column "path", :string
    t.column "user_agent", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "news", :force => true do |t|
    t.column "title", :string, :limit => 100
    t.column "language", :string, :limit => 20
    t.column "permalink", :string, :limit => 100
    t.column "random_id", :string, :limit => 50
    t.column "remote_url", :string, :limit => 100
    t.column "beta_visible", :boolean, :default => false
    t.column "live_visible", :boolean, :default => false
    t.column "headline_or_sticky", :boolean, :default => false
    t.column "headline_position", :integer, :limit => 3, :default => 0
    t.column "sticky_position", :integer, :limit => 3, :default => 0
    t.column "description", :text
    t.column "content", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "post_timestamp", :datetime
  end

  add_index "news", ["permalink"], :name => "news_permalink_index"

  create_table "news_admin_users", :force => true do |t|
    t.column "name", :string
    t.column "hashed_password", :string
    t.column "created_at", :datetime
    t.column "status", :boolean
    t.column "level", :integer
  end

  create_table "order_account_types", :force => true do |t|
    t.column "name", :string, :limit => 30, :default => "", :null => false
  end

  create_table "order_accounts", :force => true do |t|
    t.column "order_user_id", :integer, :default => 0, :null => false
    t.column "order_address_id", :integer, :default => 0, :null => false
    t.column "order_account_type_id", :integer, :default => 1, :null => false
    t.column "account_number", :string, :limit => 20
    t.column "expiration_month", :integer, :limit => 2
    t.column "expiration_year", :integer, :limit => 4
    t.column "routing_number", :string, :limit => 20
    t.column "bank_name", :string, :limit => 50
    t.column "cardholder_name", :string
    t.column "payment_type", :integer
    t.column "safe_cc_number", :string
    t.column "encrypted_cc_number", :text
    t.column "remote_ip", :string
    t.column "pfp_amount", :float
    t.column "pfp_pnref", :string
    t.column "pfp_authcode", :string
    t.column "avs_result", :string
    t.column "avs_streetmatch", :boolean
    t.column "avs_zipmatch", :boolean
    t.column "erp_recid", :string
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "remote_location", :string
  end

  add_index "order_accounts", ["order_user_id", "order_address_id", "order_account_type_id"], :name => "ids"

  create_table "order_addresses", :force => true do |t|
    t.column "order_user_id", :integer, :default => 0, :null => false
    t.column "is_shipping", :boolean, :default => false, :null => false
    t.column "telephone", :string, :limit => 20
    t.column "address", :string, :default => "", :null => false
    t.column "city", :string, :limit => 50
    t.column "state", :string, :limit => 10
    t.column "zip", :string, :limit => 10
    t.column "country_id", :integer, :default => 0, :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "shipping_label", :text
    t.column "company", :string
    t.column "address_two", :string
    t.column "first_name", :string
    t.column "last_name", :string
  end

  add_index "order_addresses", ["first_name"], :name => "order_addresses_first_name_index"
  add_index "order_addresses", ["last_name"], :name => "order_addresses_last_name_index"

  create_table "order_line_items", :force => true do |t|
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "order_id", :integer, :default => 0, :null => false
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "unit_price", :float, :default => 0.0, :null => false
    t.column "unit_deposit", :float, :default => 0.0, :null => false
    t.column "payment_method", :string, :limit => 32
  end

  create_table "order_shipping_types", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "code", :string, :limit => 50
    t.column "company", :string, :limit => 20
    t.column "is_domestic", :boolean, :default => false, :null => false
    t.column "service_type", :string, :limit => 50
    t.column "transaction_type", :string, :limit => 50
    t.column "shipping_multiplier", :float, :default => 0.0, :null => false
    t.column "flat_fee", :float, :default => 0.0, :null => false
  end

  create_table "order_status_codes", :force => true do |t|
    t.column "name", :string, :limit => 30, :default => "", :null => false
  end

  add_index "order_status_codes", ["name"], :name => "name"

  create_table "order_transactions", :force => true do |t|
    t.column "created_on", :datetime
    t.column "order_id", :integer
    t.column "transaction_id", :string
    t.column "description", :string
  end

  create_table "order_users", :force => true do |t|
    t.column "email_address", :string, :limit => 50, :default => "", :null => false
    t.column "password", :string, :limit => 20
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "name", :string
    t.column "company", :string
    t.column "store_user_id", :integer
  end

  add_index "order_users", ["email_address"], :name => "email"

  create_table "order_users_emails", :force => true do |t|
    t.column "order_users_id", :integer, :default => 0, :null => false
    t.column "real_name", :string, :limit => 50, :default => "", :null => false
    t.column "email", :string, :limit => 50, :default => "", :null => false
  end

  create_table "orders", :force => true do |t|
    t.column "order_number", :integer, :default => 0, :null => false
    t.column "created_on", :datetime
    t.column "shipped_on", :datetime
    t.column "order_user_id", :integer
    t.column "order_status_code_id", :integer, :default => 1, :null => false
    t.column "notes", :text
    t.column "referer", :string
    t.column "order_shipping_type_id", :integer, :default => 1, :null => false
    t.column "product_cost", :float, :default => 0.0
    t.column "shipping_cost", :float, :default => 0.0
    t.column "tax", :float
    t.column "auth_transaction_id", :integer
    t.column "sent_email_receipt", :boolean
    t.column "erp_order_number", :string
    t.column "erp_status_msg", :string
    t.column "erp_account_uuid", :string, :limit => 40
    t.column "erp_order_uuid", :string, :limit => 40
    t.column "erp_cc_uuid", :string, :limit => 40
    t.column "erp_complete", :boolean, :default => false
    t.column "pre_ax", :boolean, :default => false
  end

  add_index "orders", ["order_number"], :name => "order_number"
  add_index "orders", ["order_user_id"], :name => "order_user_id"
  add_index "orders", ["order_status_code_id"], :name => "status"

  create_table "participants", :force => true do |t|
    t.column "event_id", :integer
    t.column "name", :string
    t.column "email", :string
    t.column "province", :string
    t.column "city", :string
    t.column "company_name", :string
    t.column "company_website", :string
    t.column "created_at", :datetime
    t.column "address", :string
    t.column "mobile_phone", :string
    t.column "fixed_phone", :string
    t.column "reason", :text
    t.column "participanter_name", :text
    t.column "available_time", :text
    t.column "camera_type_using", :string
    t.column "scope_of_business", :string
    t.column "post_code", :string
    t.column "serial_number", :string
    t.column "deleted", :boolean, :default => true, :null => false
  end

  create_table "pfp_transaction_logs", :force => true do |t|
    t.column "pfp_serv", :string
    t.column "store_user_id", :integer
    t.column "card_name", :string
    t.column "email_address", :string
    t.column "order_number", :integer
    t.column "uuid", :string
    t.column "req_xml", :text
    t.column "res_xml", :text
    t.column "status", :string
    t.column "res_code", :string
    t.column "res_message", :string
    t.column "created_on", :date
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remote_ip", :string
    t.column "remote_location", :string
    t.column "creditcard_type", :string, :limit => 30, :default => ""
    t.column "request_header", :text
    t.column "response_header", :text
    t.column "response_code", :string, :limit => 20
  end

  create_table "product_locals", :force => true do |t|
    t.column "product_id", :integer
    t.column "cn_price", :float, :default => 0.0
    t.column "hk_price", :float, :default => 0.0
    t.column "tw_price", :float, :default => 0.0
  end

  add_index "product_locals", ["product_id"], :name => "product_locals_product_id_index"

  create_table "product_package_nodes", :force => true do |t|
    t.column "type", :string, :default => "", :null => false
    t.column "parent_id", :integer
    t.column "product_id", :integer
    t.column "name", :string
    t.column "description", :text
    t.column "position", :integer
    t.column "created_at", :datetime
    t.column "display_style", :string, :limit => 10
    t.column "additional_html", :text
  end

  add_index "product_package_nodes", ["parent_id"], :name => "product_package_nodes_parent_id_index"

  create_table "product_shipping_rates", :force => true do |t|
    t.column "shipping_zone", :string, :limit => 16, :default => "", :null => false
    t.column "code", :string, :limit => 16, :default => "", :null => false
    t.column "min_points", :float, :limit => 10, :default => 0.0, :null => false
    t.column "max_points", :float, :limit => 10, :default => 0.0, :null => false
    t.column "retail_price", :float, :default => 0.0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "products", :force => true do |t|
    t.column "code", :string, :limit => 20, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "price", :float, :default => 0.0, :null => false
    t.column "date_available", :datetime, :null => false
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "size_width", :float, :default => 0.0, :null => false
    t.column "size_height", :float, :default => 0.0, :null => false
    t.column "size_depth", :float, :default => 0.0, :null => false
    t.column "weight", :float, :default => 0.0, :null => false
    t.column "erp_product_item", :string
    t.column "deposit", :float, :default => 0.0, :null => false
    t.column "for_serial_number", :boolean
    t.column "delivery_message", :string
    t.column "accept_deposit", :boolean, :default => true, :null => false
    t.column "accept_buy_now", :boolean, :default => true, :null => false
    t.column "shipping_points", :float, :default => 0.0, :null => false
    t.column "buy_now_require_redone", :boolean, :default => true, :null => false
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
    t.column "product_status", :string
    t.column "group_id", :string
    t.column "is_featured", :boolean, :default => false, :null => false
    t.column "sequence", :integer
    t.column "end_of_line", :boolean, :default => false
    t.column "sticked", :integer, :limit => 10
  end

  create_table "products_tags", :id => false, :force => true do |t|
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "tag_id", :integer, :default => 0, :null => false
    t.column "product_sort_id", :integer
  end

  create_table "questions", :force => true do |t|
    t.column "short_question", :string
    t.column "long_question", :text, :default => "", :null => false
    t.column "answer", :text
    t.column "rank", :integer
    t.column "featured", :boolean, :default => false, :null => false
    t.column "times_viewed", :integer, :default => 0, :null => false
    t.column "created_on", :datetime, :null => false
    t.column "answered_on", :datetime
    t.column "email_address", :string, :limit => 50
  end

  create_table "red_user", :id => false, :force => true do |t|
    t.column "name", :integer, :limit => 1
  end

  create_table "redone_serial_numbers", :force => true do |t|
    t.column "ax_account_number", :string
    t.column "ax_account_id", :integer
    t.column "ax_order_number", :string
    t.column "ax_order_id", :integer
    t.column "email_address", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "serial_number", :string
    t.column "purch_order_form_num", :string
    t.column "sent_mail", :boolean, :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "reservation_items", :force => true do |t|
    t.column "reservation_id", :integer
    t.column "serial_number", :string
    t.column "description", :string
    t.column "price", :float
  end

  create_table "reservations", :force => true do |t|
    t.column "email_address", :string
    t.column "secret_code", :string
    t.column "order_id", :integer
    t.column "total", :float
    t.column "name", :string
    t.column "payment_method", :string
    t.column "source_name", :string
    t.column "source_id", :string
    t.column "paid_on", :datetime
  end

  create_table "rights", :force => true do |t|
    t.column "name", :string
    t.column "controller", :string
    t.column "actions", :string
  end

  create_table "rights_roles", :id => false, :force => true do |t|
    t.column "right_id", :integer
    t.column "role_id", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "user_id", :integer
  end

  create_table "sdk_surveys", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "company", :string
    t.column "address1", :string
    t.column "address2", :string
    t.column "city", :string
    t.column "state", :string
    t.column "zip_code", :string
    t.column "country", :string
    t.column "email", :string
    t.column "product_name", :string
    t.column "project_description", :text
    t.column "phone", :string
    t.column "mac", :boolean, :default => false
    t.column "windows", :boolean, :default => false
    t.column "fax", :string
    t.column "remote_ip", :string
    t.column "send_mailed", :boolean, :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "linux", :boolean, :default => false
    t.column "select_releases", :boolean, :default => false
    t.column "sid", :string
  end

  create_table "serial_numbers", :force => true do |t|
    t.column "account_num", :string, :limit => 20, :default => "", :null => false
    t.column "sales_id", :string, :limit => 20, :default => "", :null => false
    t.column "item_id", :string, :limit => 10, :default => "", :null => false
    t.column "serial", :string, :limit => 10, :default => "", :null => false
    t.column "serial_number", :integer, :default => 0, :null => false
    t.column "status", :string, :limit => 10, :default => "None", :null => false
    t.column "notification_sent", :boolean, :default => false, :null => false
    t.column "notification_sent_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "serial_numbers", ["account_num"], :name => "serial_numbers_account_num_index"
  add_index "serial_numbers", ["sales_id"], :name => "serial_numbers_sales_id_index"
  add_index "serial_numbers", ["serial_number"], :name => "serial_numbers_serial_number_index"
  add_index "serial_numbers", ["status"], :name => "serial_numbers_status_index"

  create_table "sessions", :force => true do |t|
    t.column "sessid", :string, :default => "", :null => false
    t.column "data", :text, :default => "", :null => false
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "sessions", ["sessid"], :name => "session_index"

  create_table "store_users", :force => true do |t|
    t.column "name", :string
    t.column "company", :string
    t.column "email_address", :string
    t.column "password", :string
    t.column "ship_to_address_id", :integer
    t.column "bill_to_address_id", :integer
    t.column "order_account_id", :integer
    t.column "security_token", :string, :limit => 40
    t.column "erp_account_number", :string
    t.column "creation_email", :boolean, :default => false, :null => false
    t.column "purchased", :boolean, :default => false, :null => false
    t.column "r3dsdk_user", :boolean, :default => false, :null => false
    t.column "post_user", :boolean, :default => false, :null => false
    t.column "red_one_user", :boolean, :default => false, :null => false
    t.column "do_not_contact", :boolean, :default => false, :null => false
  end

  add_index "store_users", ["r3dsdk_user"], :name => "store_users_r3dsdk_user_index"
  add_index "store_users", ["post_user"], :name => "store_users_post_user_index"
  add_index "store_users", ["red_one_user"], :name => "store_users_red_user_index"
  add_index "store_users", ["do_not_contact"], :name => "store_users_do_not_contact_index"
  add_index "store_users", ["email_address"], :name => "store_user_email_address"
  add_index "store_users", ["password"], :name => "store_user_password_index"

  create_table "sync_ax_products", :force => true do |t|
    t.column "product_id", :integer
    t.column "erp_product_item", :string
    t.column "name", :string, :limit => 100
    t.column "price", :float, :default => 0.0
    t.column "quantity", :integer, :default => 0
    t.column "deposit", :float, :default => 0.0
    t.column "shipping_points", :float, :default => 0.0
    t.column "product_status", :string
    t.column "group_id", :string
    t.column "dim_group_id", :string
    t.column "model_group_id", :string
    t.column "percent_deposit", :float
    t.column "amount_deposit", :float
    t.column "name_local", :string, :limit => 100, :default => ""
    t.column "name_ax", :string, :limit => 100, :default => ""
    t.column "price_local", :float, :default => 0.0
    t.column "price_ax", :float, :default => 0.0
    t.column "deposit_local", :float, :default => 0.0
    t.column "deposit_ax", :float, :default => 0.0
    t.column "shipping_points_local", :float, :default => 0.0
    t.column "shipping_points_ax", :float, :default => 0.0
    t.column "is_ignore", :boolean, :default => false
    t.column "status", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "sort_order", :integer
  end

  create_table "tickets", :force => true do |t|
    t.column "name", :string, :limit => 64
    t.column "email", :string, :limit => 64
    t.column "phone", :string, :limit => 64
    t.column "serial_numbers", :string, :limit => 64
    t.column "subject", :string
    t.column "url", :string
    t.column "user_agent", :string
    t.column "user_screen", :string
    t.column "product_type", :string, :limit => 16
    t.column "queue", :string, :limit => 16
    t.column "lang", :string, :limit => 16
    t.column "content", :text
    t.column "uuid", :string, :limit => 36, :default => "", :null => false
    t.column "submitted", :boolean, :default => false, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "tickets", ["email"], :name => "tickets_email_index"
  add_index "tickets", ["submitted"], :name => "tickets_submitted_index"
  add_index "tickets", ["uuid"], :name => "tickets_uuid_index"

  create_table "transaction_order_link", :force => true do |t|
    t.column "transaction_id", :integer
    t.column "order_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 50, :default => "", :null => false
    t.column "password", :string, :limit => 40
  end

  add_index "users", ["login", "password"], :name => "login"

  create_table "viaklix_batches", :force => true do |t|
    t.column "batch_number", :string, :limit => 10
    t.column "download_date", :datetime
    t.column "settlement_number", :string, :limit => 50
    t.column "total", :float
  end

  add_index "viaklix_batches", ["settlement_number"], :name => "settlement_number", :unique => true

  create_table "viaklix_transactions", :force => true do |t|
    t.column "transactionid", :text
    t.column "transactiontype", :text
    t.column "transactiondatetime", :text
    t.column "approvalcode", :text
    t.column "ssl_invoice_number", :text
    t.column "ssl_amount", :float, :limit => 8, :default => 0.0, :null => false
    t.column "sales_tax", :text
    t.column "cvv2_indicator", :text
    t.column "cvv2response", :text
    t.column "customer_code", :text
    t.column "card_number", :text
    t.column "exp_date", :text
    t.column "auth_response_code", :text
    t.column "auth_message", :text
    t.column "auth_source", :text
    t.column "auth_avs_response", :text
    t.column "status", :text
    t.column "ssl_amount2", :text
    t.column "ssl_avs_address", :text
    t.column "ssl_avs_zip", :text
    t.column "ssl_card_number", :text
    t.column "ssl_customer_code", :text
    t.column "ssl_description", :text
    t.column "ssl_exp_date", :text
    t.column "ssl_salestax", :text
    t.column "settlement_number", :string, :limit => 50, :default => "", :null => false
    t.column "ssl_city", :text
    t.column "ssl_email", :text
    t.column "ssl_first_name", :text
    t.column "ssl_last_name", :text
    t.column "ssl_state", :string, :limit => 50
  end

  create_table "warranty_registrations", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "company", :string
    t.column "product_categories", :string
    t.column "product", :string
    t.column "serial_number", :integer, :limit => 100
    t.column "address1", :string
    t.column "address2", :string
    t.column "city", :string
    t.column "state", :string
    t.column "zip", :integer, :limit => 10
    t.column "country", :string
    t.column "phone_number", :string
    t.column "email_address", :string
  end

end
